# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1at3ldmRfOM3xHJrGEYag1-0jwVLV8s6m
"""

import numpy as np
import matplotlib.pyplot as plt

x1 = np.linspace(-2, 2, 1001)





def f(x):
 
  if np.abs(x) > 1:
     return x
  

  elif x == -1:
     return -0.5

  elif x == 1:
    return 0.5

  else:
    return 0

 

fx1 = np.zeros_like(x1)
for i in range(0, 1001):
   fx1[i] = f(x1[i])


plt.plot(x1,fx1,'.')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(3,5,201)
fx = x**2+1
x1 = 4
fx1 = x1**2+1
plt.plot(x,fx,'k',x1,fx1,'o')
plt.show()

x1 = np.linspace(-6,-5-0.015,101)
x2 = -5
x3 = np.linspace(-5+0.015,-4,101)

gx1 = (x1**2-25)//(x1+5)
gx2 = -10
gx3 = (x3**2-25)//(x3+5)

plt.plot(x1,gx1,'k',x3,gx3,'k')
plt.plot(x2,gx2,'o',mfc = 'none')
plt.show()



import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(1,100,1001)
fx = 1/x
plt.plot(x,fx)
plt.show()

x = np.linspace(-100,0,1001)
gx = x**3+2*x
plt.plot(x,gx)
plt.show()

c = 2.5
n = 100

for n in range(1,n):
  if (1+c)**n<(1+n*c):
    print("The given statement is False")
print("(1+c)^n >= 1+n*c")